import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#45464f',
        'inverse-surface': '#2d3037',
        'on-tertiary-fixed-variant': '#763400',
        'on-primary': '#ffffff',
        'surface-bright': '#f9f9ff',
        'on-tertiary-fixed': '#321200',
        tertiary: '#000000',
        background: '#f9f9ff',
        'on-secondary': '#ffffff',
        'on-primary-fixed-variant': '#394378',
        'primary-fixed': '#dee0ff',
        primary: '#030e44',
        'surface-container-high': '#e6e8f1',
        'secondary-container': '#9df4cf',
        'on-tertiary-container': '#d2650f',
        'on-secondary-fixed-variant': '#00513b',
        'secondary-fixed-dim': '#82d7b4',
        'surface-dim': '#d7dae3',
        'surface-tint': '#515b91',
        'on-primary-fixed': '#0a164a',
        'tertiary-fixed-dim': '#ffb68c',
        'outline-variant': '#c6c5d1',
        'on-background': '#181c22',
        secondary: '#006c4f',
        'error-container': '#ffdad6',
        'tertiary-container': '#321200',
        'primary-container': '#0a164a',
        'secondary-fixed': '#9df4cf',
        'on-secondary-fixed': '#002116',
        'surface-container': '#ebedf7',
        outline: '#767680',
        'on-primary-container': '#7780ba',
        'surface-variant': '#e0e2eb',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#bac3ff',
        'on-error': '#ffffff',
        error: '#ba1a1a',
        'surface-container-highest': '#e0e2eb',
        'on-secondary-container': '#0f7255',
        'inverse-primary': '#bac3ff',
        'on-surface': '#181c22',
        'tertiary-fixed': '#ffdbc9',
        surface: '#f9f9ff',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#eef0fa',
        'surface-container-low': '#f1f3fc',
        'fintech-accent': '#5dfdc5',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
      },
    },
  },
  plugins: [forms, containerQueries],
}
